# Generated by Django 5.1.2 on 2025-01-24 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_alter_incident_options_incidentacknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='seen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='IncidentAcknowledgement',
        ),
    ]
