# Generated by Django 5.1.2 on 2025-01-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
